name: Conditional

on:
  push:
    branches:
      - main

jobs:
    welcome:
      name: "Job welcome"
      runs-on: ubuntu-latest
      steps:

        - name: "Push action"
          if: github.event_name == 'push'
          run: echo "You run push"

        - name: "Other actions"
          run: echo "You run others actions ${{github.event_name}}"
          

        
            

