name: Conditional

on:
  push:
    branches:
      - main

jobs:
    welcome:
      name: "Job welcome"
      runs-on: ubuntu-latest
      steps:
        
        - name: "Push action"
          if: github.action == 'push'
          run: echo "You run push"

        - name: "Other actions"
          run: echo "You run others actions"
          

        
            

