name: Show data from secret
on:
  push:
    branches:
      - main

jobs:
    secret-info:
      runs-on: ubuntu-latest
      steps:
        - name: Set secret as environment variable
          run: echo "GITHUB_SECRET=${{ secrets.GH_ADMIN_USER_NAME }}" >> $GITHUB_ENV

        - name: Show secret value
          run: echo "Welcome, ${{ env.GITHUB_SECRET }}"

        - name: Conditional welcome message
          if: env.GITHUB_SECRET == 'Mykola Gnatiuk'
          run: echo "Welcome, Mykola :)"
