name: Show data from secret
on:
  push:
    branches:
      - main

jobs:
  secret-info:
    env:
      CITY_NAME: London
    runs-on: ubuntu-latest
    steps:
      - name: Set secret as environment variable
        run: echo "GITHUB_SECRET=${{ secrets.GH_ADMIN_USER_NAME }}" >> $GITHUB_ENV

      - name: Show secret value
        run: echo "Welcome, $GITHUB_SECRET"

      - name: Conditional welcome message
        if: ${{ env.GITHUB_SECRET == 'Mykola Gnatiuk' }}
        run: echo "Welcome, Mykola :)"

      - name: Create new env var
        run: echo "CITY_NAME=$(echo $CITY_NAME)" >> $GITHUB_OUTPUT

  secret-info-second:
    runs-on: ubuntu-latest
    needs: secret-info
    steps:
      - name: Get value from variable
        run: echo "Welcome, $CITY_NAME"
