name: Show data from secret
on:
  push:
    branches:
      - main

jobs:
    secret-info:
      runs-on: ubuntu-latest
      steps:
        - name: Show secret value
          run: echo "Welcome, ${{ secrets.GH_ADMIN_USER_NAME }}"
