name: Show data from secret
on:
  push:
    branches:
      - main

jobs:
  secret-info:
    runs-on: ubuntu-latest

    outputs:
      CITY_NAME: London

    steps:
      - name: Set secret as environment variable
        run: echo "GITHUB_SECRET=${{ secrets.GH_ADMIN_USER_NAME }}" >> $GITHUB_ENV

      ## Secret will be automaticly masked ***
      - name: Show secret value
        run: echo "Welcome, $GITHUB_SECRET"

      - name: Create new env var
        run: echo "CITY_NAME=Warsaw" >> $GITHUB_OUTPUT

  secret-info-second:
    runs-on: ubuntu-latest
    needs: secret-info
    steps:
      - name: Get value from variable
        run: echo "Welcome, ${{needs.secret-info.outputs.CITY_NAME}}"
